language: csharp
solution: EntityFramework.DbDescriptionHelper.sln
# runtime config
mono: none
dotnet: 2.0.0
dist: trusty

install:
  - dotnet --info
  - dotnet restore
  
script:
  - dotnet build -c Release --framework:netstandard2.0 ./WeihanLi.EntityFramework.DbDescriptionHelper/WeihanLi.EntityFramework.DbDescriptionHelper.csproj